spring:
  application:
    name: spring-boot-cloud-storage

  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static:
    oci:
      compartment:
        static:
      config:
        type:
      region:
        static: