spring:
  application:
    name: spring-boot-cloud-storage

  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static:

    oci:
      adb:
        enabled: false
      function:
        enabled: false
      genai:
        enabled: false
      queue:
        enabled: false
      vault:
        enabled: false
      storage:
        enabled: true
      compartment:
        static:
      region:
        static:
      config:
        type: simple
        profile: default
        tenant-id:
        user-id:
        fingerprint:
        private-key: